### ISSUE TITLE
Installing waves package

### ISSUE THREAD

**Issue by Abiodun-Olayinka** [GoreLab/waves#23]
Hi Jenna,

Please, I am having hard times in installing the waves package in error. Here are the error messages I have been getting:
devtools::install_github("GoreLab/waves")
Downloading GitHub repo GoreLab/waves@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://api.github.com/repos/GoreLab/waves/tarball/HEAD' failed
> library(waves)
Error: package or namespace load failed for ‘waves’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 there is no package called ‘sf’
 install.packages("waves")
trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-x86_64/contrib/4.3/waves_0.2.4.tgz'
Content type 'application/x-gzip' length 3764338 bytes (3.6 MB)
==================================================
downloaded 3.6 MB

The downloaded binary packages are in
	/var/folders/ql/kkymyr817xd5r0mk7sbgq_pr0000gn/T//RtmpVRC9Zy/downloaded_packages
> library(waves)
Error: package or namespace load failed for ‘waves’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 there is no package called ‘sf’.

Thank you for your time.

Kind regards.

Abiodun.

**Comment by jmh579** [comment]
I apologize for my slow response, @Abiodun-Olayinka! I didn't have the repo set up to send me notifications for some reason, but I will fix that.

In regards to your error, it looks like one of the dependencies for waves didn't get installed correctly. I would recommend running `install.packages("sf")` and then to re-try installing waves. I recently fixed a bug in waves (update should be on CRAN shortly as v0.2.5), but this should not affect your ability to install the package.

Please let me know if you continue to have problems and I'll try to help troubleshoot.

Jenna

**Comment by Abiodun-Olayinka** [comment]
Dear Jenna,

Thank you for your support.

Problem fixed.

Kind regards.

OLAYINKA, Abiodun Fatai
Ph.D. Plant Breeding Student
West Africa Centre for Crop Improvement (WACCI)
University of Ghana
Tel: +233508643283/+2349063325862
